Mvc.AdminLTE/Models/MenuItem.cs
using System.Collections.Generic;

namespace Mvc.AdminLTE.Models
{
    public class MenuItem
    {
        public MenuItem()
        {
            Text = string.Empty;
            Controller = string.Empty;
            Action = string.Empty;
            Icon = "fa-link";
            Selected = false;
            ChildrenItems = new List<MenuItem>();
            AllowedRoles = string.Empty;
        }

        public string Text { get; set; }
        public string Controller { get; set; }
        public string Action { get; set; }
        public string Icon { get; set; }
        public bool Selected { get; set; }
        public string AllowedRoles { get; set; }
        public List<MenuItem> ChildrenItems { get; set; }
    }
}

Mvc.AdminLTE/Controllers/LayoutController.cs
using System.Collections.Generic;
using System.Web.Mvc;
using Mvc.AdminLTE.Controllers.Filters;
using Mvc.AdminLTE.Models;

namespace Mvc.AdminLTE.Controllers
{
    public class LayoutController : Controller
    {
        private readonly MenuViewModel _menuViewModel = new MenuViewModel()
        {
            MenuHeader = "MENU",
            Menu = new List<MenuItem>
                {
                    new MenuItem{ Text = "Dashboard", Icon = "fa-home", Action = "Index", Controller = "Home",},
                    new MenuItem{ Text = "Admin", Icon = "fa-cogs", Action = "Index", Controller = "Admin", AllowedRoles = "Admin", ChildrenItems = new List<MenuItem>()
                        {
                            new MenuItem { Text = "Roles", Icon = "", Action = "Index", Controller = "RolesAdmin", AllowedRoles = "Admin"},
                            new MenuItem { Text = "Users", Icon = "", Action = "Index", Controller = "UsersAdmin", AllowedRoles = "Admin"},
                            new MenuItem { Text = "Teams", Icon = "", AllowedRoles = "Admin"},
                        }
                    },
                    new MenuItem { Text = "Account", Icon = "fa-user-circle-o", Action = "Index", Controller = "Manage", AllowedRoles = "Public" , ChildrenItems = new List<MenuItem>()
                        {
                            new MenuItem{ Text = "Profile", Action = "Index", Controller = "Manage", AllowedRoles = "Public"},
                            new MenuItem{ Text = "Change Password", Action = "ChangePassword", Controller = "Manage", AllowedRoles = "Public"},
                            new MenuItem{ Text = "Manage External Logins", Action = "ManageLogins", Controller = "Manage", AllowedRoles = "Public"},
                        }
                    },
                }
        };

        [ChildActionOnly]
        [MenuItemAuthorizationActionFilter]
        [MenuItemSelectionActionFilter]
        public ActionResult _Sidebar()
        {
            return PartialView(_menuViewModel);
        }
    }
}

Mvc.AdminLTE/Views/Shared/_ControlSidebar.cshtml
<aside class="control-sidebar control-sidebar-dark">
    @* BEGIN Tabs *@
    <ul class="nav nav-tabs nav-justified control-sidebar-tabs">
        <li class="active"><a href="#control-sidebar-home-tab" data-toggle="tab"><i class="fa fa-home"></i></a></li>
        <li><a href="#control-sidebar-settings-tab" data-toggle="tab"><i class="fa fa-gears"></i></a></li>
    </ul>
    @* END Tabs *@
    <div class="tab-content">
        @* BEGIN Home Tab *@
        <div class="tab-pane active" id="control-sidebar-home-tab">
            <h3 class="control-sidebar-heading">Recent Activity</h3>
            <ul class="control-sidebar-menu">
                <li>
                    <a href="javascript::;">
                        <i class="menu-icon fa fa-birthday-cake bg-red"></i>

                        <div class="menu-info">
                            <h4 class="control-sidebar-subheading">Langdon's Birthday</h4>

                            <p>Will be 23 on April 24th</p>
                        </div>
                    </a>
                </li>
            </ul>

            <h3 class="control-sidebar-heading">Tasks Progress</h3>
            <ul class="control-sidebar-menu">
                <li>
                    <a href="javascript::;">
                        <h4 class="control-sidebar-subheading">
                            Custom Template Design
                            <span class="pull-right-container">
                                <span class="label label-danger pull-right">70%</span>
                            </span>
                        </h4>

                        <div class="progress progress-xxs">
                            <div class="progress-bar progress-bar-danger" style="width: 70%"></div>
                        </div>
                    </a>
                </li>
            </ul>
        </div>
        @* END Home Tab *@
        <div class="tab-pane" id="control-sidebar-stats-tab">Stats Tab Content</div>
        @* BEGIN Settings Tab *@
        <div class="tab-pane" id="control-sidebar-settings-tab">
            <form method="post">
                <h3 class="control-sidebar-heading">General Settings</h3>

                <div class="form-group">
                    <label class="control-sidebar-subheading">
                        Report panel usage
                        <input type="checkbox" class="pull-right" checked>
                    </label>

                    <p>
                        Some information about this general settings option
                    </p>
                </div>
            </form>
        </div>
        @* END Settings Tab *@
    </div>
</aside>
@* Add the sidebar's background. This div must be placed immediately after the control sidebar *@
<div class="control-sidebar-bg"></div>

Mvc.AdminLTE/Views/Shared/_Header.cshtml
<header class="main-header">
    @* BEGIN Logo *@
    <a href="@Url.Action("Index", "Home")" class="logo">
        <!-- mini logo for sidebar mini 50x50 pixels -->
        <span class="logo-mini"><b>CV</b></span>
        <!-- logo for regular state and mobile devices -->
        <span class="logo-lg"><b>Cash</b>Vault</span>
    </a>
    @* END Logo *@
    @* BEGIN Header *@
    <nav class="navbar navbar-static-top" role="navigation">
        <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
            <span class="sr-only">Toggle navigation</span>
        </a>
        <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
                @* BEGIN Messages *@
                <li class="dropdown messages-menu">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <i class="fa fa-envelope-o"></i>
                        <span class="label label-success">4</span>
                    </a>
                    <ul class="dropdown-menu">
                        <li class="header">You have 4 messages</li>
                        <li>
                            <ul class="menu">
                                <li>
                                    <a href="#">
                                        <div class="pull-left">
                                            <img src="~/Content/img/user.png" class="img-circle" alt="User Image">
                                        </div>
                                        <h4>
                                            Support Team
                                            <small><i class="fa fa-clock-o"></i> 5 mins</small>
                                        </h4>
                                        <p>Why not buy a new awesome theme?</p>
                                    </a>
                                </li>
                            </ul>
                        </li>
                        <li class="footer"><a href="#">See All Messages</a></li>
                    </ul>
                </li>
                @* END Messages *@
                @* BEGIN Notifications *@
                <li class="dropdown notifications-menu">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <i class="fa fa-bell-o"></i>
                        <span class="label label-warning">10</span>
                    </a>
                    <ul class="dropdown-menu">
                        <li class="header">You have 10 notifications</li>
                        <li>
                            <ul class="menu">
                                <li>
                                    <a href="#">
                                        <i class="fa fa-users text-aqua"></i> 5 new members joined today
                                    </a>
                                </li>
                            </ul>
                        </li>
                        <li class="footer"><a href="#">View all</a></li>
                    </ul>
                </li>
                @* END Notifications *@
                @* BEGIN Tasks *@
                <li class="dropdown tasks-menu">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <i class="fa fa-flag-o"></i>
                        <span class="label label-danger">9</span>
                    </a>
                    <ul class="dropdown-menu">
                        <li class="header">You have 9 tasks</li>
                        <li>
                            <ul class="menu">
                                <li>
                                    <a href="#">
                                        <h3>
                                            Design some buttons
                                            <small class="pull-right">20%</small>
                                        </h3>
                                        <div class="progress xs">
                                            @* Change the css width attribute to simulate progress *@
                                            <div class="progress-bar progress-bar-aqua" style="width: 20%" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100">
                                                <span class="sr-only">20% Complete</span>
                                            </div>
                                        </div>
                                    </a>
                                </li>
                            </ul>
                        </li>
                        <li class="footer">
                            <a href="#">View all tasks</a>
                        </li>
                    </ul>
                </li>
                @* END Tasks *@
                
                @Html.Partial("_LoginPartial")

                @* BEGIN Control Sidebar Toggle Button *@
                <li>
                    <a href="#" data-toggle="control-sidebar"><i class="fa fa-gears"></i></a>
                </li>
                @* END Control Sidebar Toggle Button *@
            </ul>
        </div>
    </nav>
</header>

Mvc.AdminLTE/Views/Shared/_Layout.cshtml
@using System.Web.Optimization
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>
        @if (!string.IsNullOrWhiteSpace(ViewBag.Title)) {
            @ViewBag.Title@: -
        }
        AdminLTE
    </title>
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <link href="~/Content/css/font-awesome.min.css" rel="stylesheet">
    <link href="~/Content/css/icheck/blue.min.css" rel="stylesheet">
    @Styles.Render("~/Bundles/css")
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body class="hold-transition skin-red sidebar-mini fixed">
    <div class="wrapper">
        @Html.Partial("_Header")
        @{ Html.RenderAction("_Sidebar", "Layout"); }

        <div class="content-wrapper">
            <section class="content-header">
                <h1>
                    @ViewBag.Title
                    <small>@ViewBag.Description</small>
                </h1>
            </section>

            <section class="content">
                @RenderBody()
            </section>
        </div>

        @Html.Partial("_ControlSidebar")
    </div>

    <script src="@RouteJs.RouteJsHandler.HandlerUrl"></script>
    @Scripts.Render("~/Bundles/js")
    @RenderSection("scripts", required: false)
</body>
</html>

Mvc.AdminLTE/Views/Shared/_MenuItem.cshtml
@model Mvc.AdminLTE.Models.MenuItem
@{
    string link;
    if (!string.IsNullOrEmpty(Model.Action) && !string.IsNullOrEmpty(Model.Controller))
    {
        link = Url.Action(Model.Action, Model.Controller);
    }
    else
    {
        link = "#";
    }
}
@if (Model.ChildrenItems.Count > 0)
{
    <li class="treeview @(Model.Selected ? "active" : string.Empty)">
        <a href="@(link)">
            <i class="fa @Model.Icon"></i> <span>@Model.Text</span>
            <span class="pull-right-container">
                <i class="fa fa-angle-left pull-right"></i>
            </span>
        </a>
        <ul class="treeview-menu @(Model.Selected ? "menu-open" : string.Empty)">
            @foreach (var menuItem in Model.ChildrenItems)
            {
                @Html.Partial("_MenuItem", menuItem);
            }
        </ul>
    </li>
}
else
{
    <li class="@(Model.Selected ? "active selected" : "")">
        <a href="@(link)"><i class="fa @Model.Icon"></i> <span>@Model.Text</span></a>
    </li>
}

Mvc.AdminLTE/Views/Shared/_Sidebar.cshtml
@using Mvc.AdminLTE.Controllers
@model Mvc.AdminLTE.Models.MenuViewModel
<aside class="main-sidebar">
    <section class="sidebar">
        @* BEGIN Search *@
        <form action="#" method="get" class="sidebar-form">
            <div class="input-group">
                <input id="menu-search" type="text" name="q" class="form-control" placeholder="Search...">
                <span class="input-group-btn">
                    <button type="submit" name="search" id="search-btn" class="btn btn-flat">
                        <i class="fa fa-search"></i>
                    </button>
                </span>
            </div>
        </form>
        @* END Search *@
        @* BEGIN Menu *@
        <ul class="sidebar-menu">
            <li class="header">@Model.MenuHeader</li>
            
            @foreach (var menuItem in Model.Menu)
            {
                @Html.Partial("_MenuItem", menuItem)
            }

            @*<li class="@(ViewContext.RouteData.Values["Action"].ToString() == nameof(HomeController.Index) ? "active" : "")">
                <a href="@Url.Action("Index", "Home")"><i class="fa fa-link"></i> <span>Home</span></a>
            </li>
            <li class="@(ViewContext.RouteData.Values["Action"].ToString() == nameof(HomeController.AnotherLink) ? "active" : "")">
                <a href="@Url.Action("Index", "Home")"><i class="fa fa-link"></i> <span>Another Link</span></a>
            </li>
            
            @if (Request.IsAuthenticated && User.IsInRole("Admin"))
            {
                <li>
                    <a href="@Url.Action("Index", "RolesAdmin")">
                        <i class="fa fa-cog"></i>
                        <span>Roles Admin</span>
                    </a>
                </li>
                <li>
                    <a href="@Url.Action("Index", "UsersAdmin")">
                        <i class="fa fa-user"></i>
                        <span>Users Admin</span>
                    </a>
                </li>
            }

            <li class="treeview">
                <a href="#">
                    <i class="fa fa-link"></i> <span>Multilevel</span>
                    <span class="pull-right-container">
                        <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">
                    <li><a href="#">Link in level 2</a></li>
                    <li><a href="#">Link in level 2</a></li>
                </ul>
            </li>*@
        </ul>
        @* END Menu *@
    </section>
</aside>